### ISSUE TITLE
ubuntu 18 taskbar menu

### ISSUE THREAD

**Issue by AMV007** [goldendict/goldendict#1097]
ubuntu 18 gnome metacity
I can see icon in taskbar, but when click on it dropdown not showed correctly - it's empty
If reenable "Enable system tray icon" in settings all working as expected
reinstalling package with deleting .goldendict directory won't help.

**Comment by vedgy** [comment]
This is probably a GNOME bug.

Workarounds:
* enable a hotkey to show the main window in Goldendict Preferences;
* if you are using the icon to toggle Scan Popup, you can apply #965 and set up a system global keyboard shortcut;
* if you right-click the icon to quit Goldendict, you could implement a corresponding command line option and assign a system global keyboard shortcut to it.

**Comment by Vladimyr0** [comment]
it's not a GNOME bug. on Unity there is the same.

**Comment by vedgy** [comment]
I suspect this is caused by lack of explicit Ubuntu Appindicator support in Goldendict.
Possible solutions:

1. Disable or remove `indicator-application` if you don't use it as advised in [the 2 answers here](https://askubuntu.com/questions/969138/tray-icons-disappears-sometimes-in-ubuntu-17-10).
2. Install the [sni-qt](https://packages.ubuntu.com/bionic/sni-qt) package as advised [here](https://askubuntu.com/questions/40145/using-appindicators-with-the-qt-framework/74817#74817).

**Comment by Vladimyr0** [comment]
I don't want to make experiments with appindicator, since on my previous install it caused the text nearby tray icons intermittently disappear. 
Now I compiled goldendict from sources for qt4 and it works frawlessly! 
So I suppose it's qt5 bug, since it also has "stay-on-top" bug and still too "raw".

**Comment by esma-eel** [comment]
i have this issue in  budgie desktop too
