### ISSUE TITLE
Some English-Arabic dictionaries do not show the whole words

### ISSUE THREAD

**Issue by sallyahaj** [goldendict/goldendict#1150]
Hello there,
I am using GoldenDict version 1.5.0-RC2+git on Fedora 30, and facing an issue with just Arabic translation, or maybe all RTL languages.
Note: If the dictionary based on LTR language everything is perfect, but if it is RTL then it depends: if it's written as the way of LTR language dictionaries then again is okay,
but if the whole dictionaries shows from right-to-left, then here the issue.

A picture below explains what I mean
![goldendict](https://user-images.githubusercontent.com/109706/57134815-f3094780-6dc4-11e9-9cff-8f3bfbd66db8.png)

**Comment by Michahel** [comment]
Hi jalalsfs,

I guess it's specific to Fedora. Give the opportunity to download dictd dictionary "Arabeyes Technical Computing Dictionary", so will check it out on the XP machine and see if I can reproduce it.

**Comment by vahid75** [comment]
no its not specific to fedora.i have ubuntu disco and the problem exists.i resize the article page width to 50% of page width and when i resize the window the problem solved but its a temporary solution.can anyone have a right solution??tnx

**Comment by Michahel** [comment]
Despite all this, I still checked on Windows XP. I configured GoldenDict on the server dict.arabeyes.org. The screen capture shows that in Windows XP when using the DICT server there is no problem. [See screen capture](https://yadi.sk/i/WvS3MXso8jLhEw)

**Comment by shabahengam** [comment]
in my tests this problem only happens if you compile the project with qt5 and if you compile the project with qt4 there is no problem.check this pictures.[qt4](https://0x0.st/zOed.png) vs [qt5](https://0x0.st/zO2f.png)
the main problem is in [here](https://github.com/goldendict/goldendict/blob/master/article-style.css#L84).for example if i edit [bglrtl class](https://github.com/goldendict/goldendict/blob/master/article-style.css#L104) and change the "text-align: right" to "text-align: center" this happens: [before](https://0x0.st/zO2j.png) vs [after](https://0x0.st/zO2a.png)
as far as i know qt4 use webkit and qt5 use webengine for rendering css files.
i hope this informations helps you to fix the problem.
ps. sorry for my english.

**Comment by Fahad-Alsaidi** [comment]
I notice this problem when I try to use [Al-Mawrid](https://github.com/dolanskurd/Al-Mawrid) dict in Kde neon linux. I got translation overflown
![image](https://user-images.githubusercontent.com/1632566/76700924-d2dd3100-66d5-11ea-9854-6fc56ed4b291.png)
but when I tested on Windows it works fine:
![image](https://user-images.githubusercontent.com/3102714/76797024-9a3d7480-6807-11ea-8c04-92c9a39aaecc.png)
I am using 1.5.0-RC2-422-g353ea17 build from master

**Comment by shahab-vahedi** [comment]
This has something to do with `qt5-webkit`. I am able to reproduce the same issue in another program ([qutebrowser](https://qutebrowser.org/)). In `qutebrowser` one can set the rendering backend to `webengine` (default) or `webkit`.

I saved a sample _html_ from GoldenDict and opened it in `qutebrowser` with 2 different backends:

## webengine
![qt5-webengine](https://user-images.githubusercontent.com/16524902/79042594-5fa5dc80-7bf9-11ea-9c89-2f52ea68d737.png)

## webkit (same as goldendict):
![qt5-webkit](https://user-images.githubusercontent.com/16524902/79042595-63d1fa00-7bf9-11ea-97c9-65f157a98ee0.png)

I also confirm that this was not a problem with `qt4-webkit`. To be honest I don't have high hopes for this issue to be resolved. I am focusing my efforts on recompiling `goldendict` statically with `qt4-webkit`. Although, if someone wants to fix this for `goldendict` I am willing to donate some.

P.S.: The sample html is attached here.
[impetuous.zip](https://github.com/goldendict/goldendict/files/4464528/impetuous.zip)

**Comment by ilius** [comment]
It works perfectly with Qt4.
For other users, here is how to build with Qt4 on Debian-based systems:
https://gist.github.com/ilius/0fef65b0512e1f8fa7c2d258be98c515

**Comment by footing11** [comment]
That's true, if you compile it from binary with qt4-qmake it fixes this issue. 
But qt4 is old and is not supported after debian 10. We don't have it on Bullseye.
So please fix this issue on application when compiling using qt5.
Thanks,

**Comment by hosein2398** [comment]
Any update on this one?

**Comment by sallyahaj** [comment]
> Any update on this one?

The last release of the app was in 2016, I think it's better to look for other alternatives.

**Comment by hosein2398** [comment]
Why did you close the issue, repository has been updated few days ago, so there is still a chance of this issue being fixed in the future. And btw, there is no true alternative for this software out there.

**Comment by hosein2398** [comment]
If you want a quick fix as @ilius has mentioned, you can build the software with qt4. But my problem is that qt4 is no more supported in Ubuntu 22. 
https://gist.github.com/ilius/0fef65b0512e1f8fa7c2d258be98c515

Another solution which I came through (in https://github.com/goldendict/goldendict/issues/1081) was this build of application with qt6,
[GoldenDict-x86_64.AppImage](https://www.mediafire.com/file/3o2eaw547jn8ug0/GoldenDict-x86_64.AppImage/file)
more info: 
https://www.pdawiki.com/forum/forum.php?mod=viewthread&tid=44300&extra=page%3D1&_dsign=3a2b8a89
But this also wasn't useful since it hangs up while using it.

**Comment by xiaoyifang** [comment]
try this https://github.com/xiaoyifang/goldendict/releases

**Comment by hosein2398** [comment]
Problem solved!‌ 
Thanks @xiaoyifang, your fork is great. 

As a suggestion, I think it's better to provide more information in README and About section of the repo, so that people will have a view of what sort of issues the fork solves.

**Comment by sallyahaj** [comment]
> try this https://github.com/xiaoyifang/goldendict/releases

Thank you so much for the all your work.

**Comment by ilius** [comment]
I have added links to your fork:
https://github.com/ilius/pyglossary/blob/master/doc/p/stardict.md#dictionary-applicationstools

Thanks.
