### ISSUE TITLE
[Qt 4 only] Bad characters in abbreviations hints

### ISSUE THREAD

**Issue by Unchqua** [goldendict/goldendict#1224]
Noticed this for every abbreviation hint which has "-" in it. This is an ordinary char with code 0x2d, Unicode HYPHEN-MINUS U+002D.
![hint](https://user-images.githubusercontent.com/56184/72521995-acce1880-386d-11ea-8862-3e6ed6f9466b.png)
OS Windows 7, GoldenDict 1.5.0-RC2-372 (Qt 4.8.6).
But Qt 5.12.3 displays it right. Should we consider Qt 5 builds "the future of GoldenDict" and not to work with Qt 4 ones?

**Comment by xiaoyifang** [comment]
any dictionary to test?

**Comment by Unchqua** [comment]
Not reproducible now. My current OS is now (way outdated) Windows 8, and hints display right both with Qt 4.8.6 and 5.12.3.

**Comment by vedgy** [comment]
> Should we consider Qt 5 builds "the future of GoldenDict" and not to work with Qt 4 ones?

[Qt 4 was first released in 2005 and has been unsupported since 2015.](https://en.wikipedia.org/wiki/Qt_version_history#Qt_4) So in general fixing Qt4-specific bugs is unrewarding, to say the least. I personally would love to drop Qt 4 support from GoldenDict master. This would facilitate several refactorings, which I wanted to do in #1542 but delayed till Qt 4 is no longer supported to avoid a lot more `#ifdef`-ing.
