### ISSUE TITLE
[XDXF] Fails to search / index Swedish words with diacritics

### ISSUE THREAD

**Issue by ashwinvis** [goldendict/goldendict#1383]
Version: goldendict 1.5.0RC2-9
OS: ArchLinux

I use this [Swedish-English dictionary developed at KTH (approximately 13 MB)](https://folkets-lexikon.csc.kth.se/folkets/folkets_sv_en_public.xdxf). I managed to add it into GoldenDict and it works for words without diacritics like "**vem, var**..." (who, where). However if I check "**varför**" (why) I get:

_**No translation for varför was found in group All**_

If I open the file I can see that it is defined:

```xml
  <ar>
    <k>varför</k>
    <def>
      <gr>ab</gr>
      <dtrn>why</dtrn>
      <tr>vAr:fö:r</tr>
      <iref href="http://lexin.nada.kth.se/sound/varf0366r.mp3" />
      <sr><kref type="syn">hurså</kref></sr>
      <iref href="http://spraakbanken.gu.se/ws/saldo-ws/fl/html/varför" />
      <ex type="exm"><ex_orig>varför gråter du?</ex_orig><ex_transl>varför gråter du?</ex_transl>      </ex>
      <ex type="exm"><ex_orig>varför det?</ex_orig><ex_transl>varför det?</ex_transl>      </ex>
      <ex type="exm"><ex_orig>jag undrar varför hon skrattade</ex_orig><ex_transl>jag undrar varför hon skrattade</ex_transl>      </ex>
      <ex type="exm"><ex_orig>varför inte?</ex_orig><ex_transl>varför inte?</ex_transl>      </ex>
      <def>av vilken anledning</def>
    </def>
  </ar>
```

But if I activate Swedish Wiktionary, GD is capable of searching and displaying the result. No helpful error messages appear in the terminal. This issue is possibly a related to #1128?

**Comment by nonwill** [comment]
Can you test the version of my private build? I just simply tested "varför" and “vem” and it seems no problem with diacritics.
![20210525102601](https://user-images.githubusercontent.com/46510529/119430829-0983f200-bd44-11eb-99fd-c31cc1a7b8e5.png)

The builds and documents are available on [GoldenDict++OCR](https://autoptr.top/gdocr/). And you can always download them directly from [OneDrive](https://1drv.ms/u/s!AllBS8YFxXjJbFGwCu3UQ6k4Ft4?e=4d8nbd).

**Comment by ashwinvis** [comment]
@nonwill Thanks... can you point me to the source code? I would rather build it myself.

**Comment by nonwill** [comment]
@ashwinvis
 I'm sorry source code is not available now for that individual commercial companies or person in our country (may be) using it to make a profit.  I do not like to work for them who have no morals.

**Comment by ashwinvis** [comment]
The original code is GPLv3 licensed. I hope you are aware that if you are distributing the builds you are obliged to distribute the source code too.

**Comment by nonwill** [comment]
> The original code is GPLv3 licensed

Yes. So I just closed the repo and just make it a private build to avoid troubles. But an Early Snapshot which is not merged into the official repo is here：
https://github.com/goldendict/goldendict/pull/1129

**Comment by vedgy** [comment]
> Yes. So I just closed and removed the repo and just make it a private build to avoid troubles. But an Early Snapshot which was not merged into the official repo is here：
#1129

Removing the repo doesn't free you from the GPL responsibility. The source code must be distributed along with the binaries regardless of whether you designate the build "private" or not. Pointing to an older version of the code, which differs from the version used to build the distributed binaries, is not sufficient to comply with the GPL.

What you are doing now goes against both the letter and the spirit of the GPL. The users must either use the official free version or your **proprietary** version with alleged improvements and fixes. But the users are powerless to further improve or modify your version to suit their tastes, or to fix some bug you haven't. Furthermore, there is no way to tell whether the builds you distribute contain hidden antifeatures or malware. @ashwinvis is probably concerned about the security implications of running non-free _["free" as in "free speech", not as in "free beer"]_ binaries distributed by a stranger on the Internet.

> I'm sorry source code is not available now for that some individual commercial companies or person (may be) using it to make a profit. I do not like to work for them who have no morals.

That's what the copyleft GPL protects us from. The moralless companies or individuals cannot improve or fix the code, then sell their versions - unless they distribute the source code too, in which case everyone can build and distribute the same improved/fixed version themselves for free. See https://www.gnu.org/licenses/quick-guide-gplv3.html (use the language button in the top right corner to read the explanation in your preferred language).

**Comment by vedgy** [comment]
@ashwinvis, I downloaded the dictionary you linked to, and the word "varför" is translated like on @nonwill's screenshot in my almost-latest-master GoldenDict in Manjaro. You can use [the AUR GoldenDict package](https://aur.archlinux.org/packages/goldendict-git/) to build the latest master version.

**Comment by nonwill** [comment]
> That's what the copyleft GPL protects us from. The moralless companies or individuals cannot improve or fix the code, then **sell** their versions

Yes, that‘s the point. I do not trust those who distribute free software for profit. So, I just made a choice and users can also make their choice. 

Can you and the officials of GoldenDict direct your attention to those profitable companies or individuals who violate the GPL agreement and just give us timely and reliable build for supporters, or be lenient and friendly to newer contributors?

**Comment by ashwinvis** [comment]
@vedgy Thanks, I will check it out. Meanwhile I managed to use pyglossary and also improve its XDXF -> IFO conversion to reveal to circumvent this issue and also reveal the pronounciation links.

@nonwill Reach out to https://sfconservancy.org/copyleft-compliance/ and https://www.gnu.org/licenses/gpl-violation.html . But before doing so make yourself complaint to work towards upstreaming the changes.

**Comment by nonwill** [comment]
> Reach out to https://sfconservancy.org/copyleft-compliance/ and https://www.gnu.org/licenses/gpl-violation.html

Thanks. All content is clear here.

**Comment by ashwinvis** [comment]
I confirm it works on the git version. Thanks again.

**Comment by vedgy** [comment]
> Can you and the officials of GoldenDict direct your attention to those profitable companies or individuals who violate the GPL agreement, and just give us timely and reliable build for supporters, or be lenient and friendly to newer contributors? That would be better.

1. Do you have some existing specific company or individual violations of GoldenDict's GPL? So far, you are the only violator that I am aware of :) Companies are usually well aware of the GPL requirements and rarely violate them nowadays. When they do, they risk receiving cease and desist letters, which would mean wasted development effort, money and reputation loss, or even hefty fines.
2. I agree that the current situation with the official builds is problematic. Judging from #1322, GoldenDict maintainers don't provide clear enough instructions about building working versions on Windows. I don't use Windows and would rather not even run it in a virtual machine due to privacy and security concerns. The situation on Mac doesn't look good either: https://ports.macports.org/port/goldendict/builds
You can help by posting detailed Windows and Mac build instructions e.g. in the GoldenDict Wiki or even create a pull request that adds these instructions to the official GoldenDict README.md. I mean: where to download or how to build all the libraries GoldenDict depends on, and how to build GoldenDict itself.
You can also contribute to the GoldenDict Portfile on MacPorts.
3. The first problem with #1129 was that it added binaries, which GoldenDict maintainers couldn't trust. Even if the binaries could be verified by comparing their hash sums with their official versions, not wanting to bloat the main GoldenDict repository with platform-specific binaries is a valid reason to reject such a pull request. These binaries are useless for e.g. GNU/Linux users, yet they would have to download them (and each updated version of them!) every time they clone GoldenDict repository. Perhaps it would be better to create a separate repository with the required Windows and Mac binaries, with links/instructions - where to download/how to build. See e.g. such old repositories: https://github.com/Tvangeste/goldendict-winlibs, https://github.com/Tvangeste/goldendict-winlibs-prebuilt.
4. Another problem with #1129 was that all the later improvements and fixes were combined in the same pull request, the first commit of which the maintainers weren't willing to merge. If you create small focused pull requests, they have a better chance of being reviewed and merged. If not and your **free** fork is indeed much better than the official version, in time users and contributors will switch to your version, eventually making it the most widely used version. At some point it could be renamed to something other than "GoldenDict" and gradually replace GoldenDict (almost) everywhere.

**Comment by vedgy** [comment]
1. Are you sure these are GPL violations? The GoldenDict apps on Google Play (https://play.google.com/store/apps/details?id=mobi.goldendict.android and https://play.google.com/store/apps/details?id=mobi.goldendict.android.free) are distributed by the owner of the official GoldenDict site http://goldendict.org. I assume the original author of GoldenDict - @dragonroot - is behind them. http://goldendict.mobi/legal.php - this page describes all 3rd-party dependencies of the Android app. Looks like the license compatibility is carefully examined and ensured. As far as I know, the Android application has been created before GoldenDict started accepting external contributions under the terms of the GPL. I assume that the GPL-only improvements and fixes are *not* incorporated/merged into the mobile version without an explicit permission from their authors. Though I don't know for sure as I have never used the Android version.
4) You are right that large code contributions to GoldenDict often require lots of patience. It is understandable that not everyone is willing to do this. Still, if you make your code available, some sort of a solution/merge could be found. Perhaps other developers would be willing to review your changes and suggest improvements, or create small pull requests (cherry-picks) for this official repository.

**Comment by nonwill** [comment]
1.  I'm not talking about the mobile platform but GoldenDict of PC platform.  "I assume the original author of GoldenDict - @dragonroot - is behind them." Yes, I believe that. Maybe it's their private collaboration.

4. Things will not be changed if specific company or individual violations of GoldenDict's GPL are still exist -- I am just one powerless to change them and do things just to make GoldenDict more accessible to young students here.

**Comment by vedgy** [comment]
1. I cannot find where GoldenDict desktop version is being sold. The only version I have found is a suspected spyware discussed in #1319.
2. If some of the young students you care about study software engineering, they may want to contribute and fix/improve the GoldenDict version they are using. Yet this freedom is denied to them.

**Comment by nonwill** [comment]
1. The sold one I knew is not called GoldenDict but with GoldenDict sources and is **static** compiled/build. I can't give its name here because I don't want to get myself into unnecessary troubles, but you can get some information on related history posts from pdawiki and freemdict in which I have given a brief analysi if they are still there. I know nothing about #1319.
2. I don't agree with you -- Teenagers at the basic education level may not have that ability and awareness. College students are free to choose the version they love, and no one will force them -- which one they love is their free.

**Comment by nonwill** [comment]
@vedgy It's time to stop this discussion. I don't care about a tree that has been sentenced to death. But if the moths are removed, I will still insist on watering it. Wish you a good night.

**Comment by marreromarco** [comment]
@vedgy 

GoldenDict Desktop is being sold by a Chinese Company and by an individual developer from China called "nonwill".

nonwill did not contribute with a line of code but has more than 80.000 users of his private fork and asks for "donations". He is blatantly violating GPL.

https://v2ex.com/t/804545
