### ISSUE TITLE
https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Mac-OS-X

### ISSUE THREAD

**Issue by ivanduka** [goldendict/goldendict#1427]
Hi,

Thank you for maintaining this awesome project! Are there any plans for new **MacOS Early Access Builds**? The last one we have was released on 27 April 2019.

Thanks,
Ivan

**Comment by andradadad** [comment]
Windows also has been more than 2 years without any updates.

Seems like a dead project, but the history of commits show contrarily an intense source-code development.

**Comment by ivanduka** [comment]
Maybe it is actively developed only for Linux?

**Comment by quantissimo** [comment]
Personally, I hope that some user (with the necessary skills and knowledge) will compile it for MacOS and share it with the rest of us. I can see that the developers are not committed to release any Windows or Mac builds

**Comment by itkind** [comment]
> Personally, I hope that some user (with the necessary skills and knowledge) will compile it for MacOS and share it with the rest of us. I can see that the developers are not committed to release any Windows or Mac builds

Yes they are, at least for windows but not here. The developer is releasing builds in the russian forum. Here is the latest one: https://www.mediafire.com/file/svmblzndfuezvrt/goldendict-1.5.0-RC2-497-gb10cdf6%2528EXE_only%2529.7z/file
The link to the forum: http://forum.ru-board.com/topic.cgi?forum=5&topic=49149&start=2800#14

**Comment by itkind** [comment]
Hi people. I hired someone on fiverr to compile a new macos version of GD based on intel (since no qt5 on M1 yet). Meanwhile I managed to run GD through crossover on my M1 based on the new windows version from the ru-board. It works good, there are some things that don’t work like the popup throughout all applications but this is only a temporary solution.
<img width="1499" alt="2021-12-05_21-06-22" src="https://user-images.githubusercontent.com/22380863/144762615-d6569a67-d30e-4f1f-8fda-d709895793f0.png">

**Comment by shawkynasr** [comment]
> (since no qt5 on M1 yet)

I think will be QT6 on M1.
If don't use mdx dicts, I recommend you [nowill version for mac](http://files.autoptr.top/f/tempdir-BWdWYAE6AW9bYQBjCTEHZAMsU2cGNFxsWDVYOFM-UmcKbFJlBSoLYgE1VDBXbgdtDj0HN1BoCzJcMA). it fixed many bugs and so stable.

**Comment by itkind** [comment]
> I think will be QT6 on M1.
It will also be on QT5. 

> it fixed many bugs and so stable.
It is really good but I wonder why it is on Qt 5.9.9 and not 5.15.

**Comment by shawkynasr** [comment]
> > I think will be QT6 on M1.
> > It will also be on QT5.
> 
> > it fixed many bugs and so stable.
> > It is really good but I wonder why it is on Qt 5.9.9 and not 5.15.

He wrote: macOS 继续使用当前 GoldenDict++ 所用开发环境，考量升级到 Qt-5.12.12；
macOS continues to use the current development environment used by GoldenDict++, considering upgrading to Qt-5.12.12;
Later, will be upgraded

**Comment by nonwill** [comment]
> If don't use mdx dicts, I recommend you [nowill version for mac](http://files.autoptr.top/f/tempdir-BWdWYAE6AW9bYQBjCTEHZAMsU2cGNFxsWDVYOFM-UmcKbFJlBSoLYgE1VDBXbgdtDj0HN1BoCzJcMA). it fixed many bugs and so stable.

mdx has no problem to render. The measure to block freemdict or pdawiki is simply to keep younger students here away from the propaganda of scammers.

>It is really good but I wonder why it is on Qt 5.9.9 and not 5.15.

On windows, Qt-5.9.9-patched is with some bugfixs and features of Qt-5.12 and Qt-5.15 back ported. The improvement is the avoidance of memory leaks in Qt5.12 and Qt5.15, as well as support for the latest openssl.
But the mac one is difficult for that the performance of my device is too poor to build QtWebkit with newer version of Qt.

**Comment by nonwill** [comment]
> If don't use mdx dicts, I recommend you [nowill version for mac](https://www.autoptr.top/gdocr/). 

mdx has no problem to render by [GoldenDict++](https://www.autoptr.top/gdocr/) now. The measure to block freemdict or pdawiki is simply to keep younger students here away from the propaganda of scammers, which is specific to the needs of specific users, but not incorporates malicious features claimed by scammers.

>It is really good but I wonder why it is on Qt 5.9.9 and not 5.15.

On windows, [Qt-5.9.9-patched](https://www.autoptr.top/gdocr/GoldenDict-OCR-Changelog/) is with some bugfixs and features of Qt-5.12 and Qt-5.15 back ported. The improvement is the avoidance of memory leaks in Qt5.12 and Qt5.15, as well as support for the latest openssl.
But the mac one is difficult for that the performance of my device is too poor to build QtWebkit with newer version of Qt.

> it fixed many bugs and so stable.

If GoldenDict would fix the buffer overflow vulnerability and [JavaScript privilge escalation issue](https://www.autoptr.top/gdocr/GoldenDict-JavaScript-Privilge-Escalation/), it should be a very stable and secure one too.

**Comment by shawkynasr** [comment]
**For mdx, I recommend to using [official MDict for Mac](https://apps.apple.com/us/app/mdict/id389083586).**

> mdx has no problem to render by [GoldenDict++](https://www.autoptr.top/gdocr/) now. The measure to block freemdict or pdawiki is simply to keep younger students here away from the propaganda of scammers, which is specific to the needs of specific users, but not incorporates malicious features claimed by scammers.

I avoid distributing users with this topic, the truth is you have personally problems with some Chinese users (Country-mate)... **You don't have any right to block any website, that [GDPR](https://gdpr-info.eu/).**

Authors of mdx files same like dsl, **that not funny you destroyed rendering for mdx**... which is not acceptable at all.

> which is specific to the needs of specific users

**You want punish them by destroying rendering of mdx! so that's ridiculous.**

**Comment by nonwill** [comment]
>the truth is you have personally problems with some Chinese users (Country-mate)... 

> You want punish them by destroying rendering of mdx! so that's ridiculous.

But seems to be harmless to them. From your standpoint, what you are promoting is also fine and should not be rejected, just [as vedgy said](https://github.com/goldendict/goldendict/issues/1424#issuecomment-965376250):
>Public opinion in most countries sympathizes with Chinese political prisoners and would trust them more than sites approved by Chinese government.

The truth is that we refuse to drive traffic to scam-related websites as some ridiculous users or developers doing:
>https://www.pdawiki.com/forum/thread-45788-1-1.html
![](https://z3.ax1x.com/2021/11/15/IgiluQ.jpg)

**Comment by GPLv3-fan** [comment]
> The truth is that we refuse to drive traffic to scam-related websites as some ridiculous users or developers doing:

@nonwill, you are an avid user of PDAWiki and FreeMDict. You lurk in those forums all day long, seeing what others are saying about your malware GD++.  The only scammer here is @nonwill who steals code from the Official GoldenDict to incorporate malicious features, spy users, make money and censor a free internet.

@nonwill is a proud member and promotes the Chinese Communist Party. Her actions are typical of believers of authoritative regimes. This 2021, nonwill even promotes on her GD++ the _"100th Anniversary of the Chinese Communist Party"_ and users cannot deactivate such propaganda on the GD++.

The "[Black Book of Communism"](https://en.wikipedia.org/wiki/The_Black_Book_of_Communism) describes how @nonwill favorite ideology has killed >100 million persons worldwide. Only in China, 65 million persons died due to Communism, and @nonwill celebrates that in her GD++ malware. SHAMEFUL !

 **Everyone should delete that GD++ malware ...**

**Comment by shawkynasr** [comment]
Everyone represent himself, I didn't said like @vedgy 

@vedgy [main point stand with GPL](https://github.com/goldendict/goldendict/issues/1424#issuecomment-985600697), others personal views is his own.

> The truth is that we refuse to drive traffic to scam-related websites as some ridiculous users or developers doing:
> https://www.pdawiki.com/forum/thread-45788-1-1.html

What do you mean? Pdawiki didn't scam any user, from 2008 till now, a lot of mdx files made it by them, 99% dicts from pdawiki..other web like free things 白嫖, **it's OK, they are free.**

FYI, Russian websites same, that is [forum](http://forum.ru-board.com/topic.cgi?forum=93&bm=1&topic=3774&start=5780), here for [paid dicts](http://lingvodics.com/dics/view/paid/), [other one free](http://dadako.narod.ru/paperpoe.htm)

**So Your next step block [Russian forum](http://forum.ru-board.com/topic.cgi?forum=5&topic=49149&start=2820) and destroy rendering for DSL and LSD, because they are scammers!**

Others users disturbing you or rude to you represent themselves, you can't close everyone mouth, you can't stop the rumour mill from turning. **They said: "Your GD++ have malware", not all of people believe it.** These people who angry with you, they are willing using, they hate pdawiki more than hate you. **So, Don't take it seriously**

My advice to you, if they made mistakes, No need make bigger mistakes!

**Comment by nonwill** [comment]
@shawkynasr : 

>What do you mean? Pdawiki didn't scam any user

I am well aware of your concerns and I think I have expressed myself clearly in the email exchange with you:
![sn_pda](https://user-images.githubusercontent.com/46510529/144976253-51e74d00-69cb-46e3-b82a-f7808a29d826.png)

> So Your next step block [Russian forum](http://forum.ru-board.com/topic.cgi?forum=5&topic=49149&start=2820) and destroy rendering for DSL and LSD, because they are scammers!

This is just your speculation, not ours.

> Others users disturbing you or rude to you represent themselves, you can't close everyone mouth, you can't stop the rumour mill from turning. **They said: "Your GD++ have malware", not all of people believe it.** These people who angry with you, they are willing using GD, they hate pdawiki more than hate you. **So, Don't take it seriously**

>My advice to you, if they made mistakes, No need make bigger mistakes!

That is the truth. However, we do not have resources to perfect custom versions of GoldenDict++ for specific users or groups. 
When everybody adds fuel the flames rise high. Just as some of those from freemdict and pdawiki who are now improving GD for OCR support, we don't care them scam-related or not because they are doing good things for users. But everyone has their own position - 道不同, 不相为谋.

**Comment by VimWei** [comment]
The villain sues his victim before he himself is prosecuted.

**Comment by nonwill** [comment]
Just as @VimWei , [Vim](https://forum.freemdict.com/u/vim) or [VimVim](https://www.pdawiki.com/forum/space-uid-289999.html), the Rotten God says, Scammers never admit they are scamming, until they are caught.

**Comment by ivanduka** [comment]
For everyone who is trying to make sense of this situation, nonwill created a build of GoldenDict for Macos (called GoldenDict++ or GD++), but for political reasons removed some functionality (ability to read some types of dictionaries?) to deny service to their political opponents.
In the build, on the first screen nonwill made their political affiliation very clear by displaying a huge banner glorifying the Communist Party of China.
The 'scammers' nonwill referring to in many of their messages are their political opponents, i.e. anyone who is not a fan of the Communist Party of China.
The opponents of nonwill mentioned that there are serious suspicions that the build contains some malicious code, possibly even spyware, as well as some censorship tools.

**Comment by nonwill** [comment]
@shawkynasr : Sorry, your English seems to be as difficult for me to understand as your Chinese.
If scammers mean everybody you prefered, please keep in touch via our email, or in your forums. 
But here let's end this topic.

**Comment by itkind** [comment]
It seems that QT5.15 doen't work well with GD. Take a look: https://drive.google.com/file/d/1C11DJO8Y95Kb_GqUOKCEIzhB1QYlbzbA/view?usp=sharing

Issues: 
Font size is not saved
Some dictionaries are not indexing 
Some images are not loading 
Can't disable dictionaries by dragging them into the disable window.

**Comment by nonwill** [comment]
@itkind 
> It seems that QT5.15 doen't work well with GD. Take a look:

The mac version of GoldenDict++OCR is based on Qt-5.9 and I know nothing about the Qt-5.15 one that you mentioned. 

But as mentioned in your recent post, if you have purchased something that is not up to par, then you can contact the aftermarket to fix the problem.

**Comment by itkind** [comment]
@nonwill
I did't purchase the software, I paid someone to compile it for me from Github using Qt5.15. The result I shared in the google drive link. This is an issue with Qt5.15. Similar issue we see in Qt5.12 here: https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Mac-OS-X

**Comment by nonwill** [comment]
>I did't purchase the software,  paid someone to compile it for me from Github using Qt5.15

@itkind : I know nothing about it. So pinging the one you paid or the developer of the repo maybe the best idea.

**Comment by itkind** [comment]
@nonwill
Will you be able to resolve the issue with cmd+c+c in your version?

**Comment by itkind** [comment]
There is also an issue with searching the current article by shortcut cmd+f in your version

**Comment by GPLv3-fan** [comment]
> @nonwill Will you be able to resolve the issue with cmd+c+c in your version?

@nonwill is busy adding malicious feaures to its GD-- spyware. Many bugs request to nonwill are not solved because he just occupies herself on grabbing data from users for a profit and attacking her opponents... GD-- should be deleted from users PCs instead. 

@itkind running Linux on your Mac device might be an option to use GoldenDict .
https://9to5mac.com/2021/10/07/linux-is-now-usable-as-a-basic-desktop-for-m1-macs/

**Comment by GPLv3-fan** [comment]
@shawkynasr **Are you still donating your money to malware developer "nonwill" ?**

hmmm.... It is curious how you began defending "nonwill" so passionately and even donating regularly. 

@shawkynasr  you even criticized "tovaremeterio" because it was banned from PdaWiki. Now your idol nonwill is also banned ! Enjoy !

**Comment by xiaoyifang** [comment]
https://github.com/goldendict/goldendict/issues/1340#issuecomment-1037220952

**Comment by prenfic** [comment]
> [#1340 (comment)](https://github.com/goldendict/goldendict/issues/1340#issuecomment-1037220952)
> macos release ,wish someone can verify it. and expected to receive commits

Non working with arm64 OS 12.1

`-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               GoldenDict [14304]
Path:                  /Applications/GoldenDict.app/Contents/MacOS/GoldenDict
Identifier:            org.goldendict
Version:               22.2 (???)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-02-17 04:08:05.8341 +0800
OS Version:            macOS 12.1 (21C52)
Report Version:        12
Anonymous UUID:        A6B6719C-C5F7-9E96-8FDB-FF960C9921D3

Sleep/Wake UUID:       551F09B0-FD77-4330-B52E-FCFCBA35BCDC

Time Awake Since Boot: 120000 seconds
Time Since Wake:       4878 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/libopencc.1.1.dylib
Referenced from: /Applications/GoldenDict.app/Contents/MacOS/GoldenDict
Reason: tried: '/Applications/GoldenDict.app/Contents/MacOS/../Frameworks/libopencc.1.1.dylib' (no such file), '/Applications/GoldenDict.app/Contents/MacOS/../Frameworks/libopencc.1.1.dylib' (no such file), '/usr/local/lib/libopencc.1.1.dylib' (no such file), '/usr/lib/libopencc.1.1.dylib' (no such file)
(terminated at launch; ignore backtrace)

Application Specific Information:
Library not loaded: @rpath/libopencc.1.1.dylib
Referenced from: /Applications/GoldenDict.app/Contents/MacOS/GoldenDict
Reason: tried: '/Applications/GoldenDict.app/Contents/MacOS/../Frameworks/libopencc.1.1.dylib' (no such file), '/Applications/GoldenDict.app/Contents/MacOS/../Frameworks/libopencc.1.1.dylib' (no such file), '/usr/local/lib/libopencc.1.1.dylib' (no such file), '/usr/lib/libopencc.1.1.dylib' (no such file)


Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x100d32940 ???
1   <translation info unavailable>	       0x100d82fec ???
2   dyld                          	       0x200c5b201 abort_with_payload + 9
3   dyld                          	       0x200c09613 dyld4::halt(char const*) + 375
4   dyld                          	       0x200c0555d dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3955
5   dyld                          	       0x200c044b4 start + 388

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffd748e4 0x7ff7ffd70000 + 18660
1   runtime                       	    0x7ff7ffd81928 0x7ff7ffd70000 + 71976
2   runtime                       	    0x7ff7ffd830a4 0x7ff7ffd70000 + 77988


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x00000003050adad0   x3: 0x0000000000000066
    x4: 0x00000003050ad6d0   x5: 0x0000000000000000   x6: 0xd503201f30257ca4   x7: 0x0000002052800661
    x8: 0x00000003050ad6d0   x9: 0x0000000000000000  x10: 0x0000000000000066  x11: 0x00000003050ad6d0
   x12: 0x0000000000000066  x13: 0x00000003050adad0  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x8000000108d9bb70  x19: 0x0000000100d28000
   x20: 0x00000000000007ff  x21: 0x0000000108da0fa0  x22: 0xffffffffffffffff  x23: 0x0000000100d32914
   x24: 0x0000000200c5b1cf  x25: 0x0000000100d321f4  x26: 0x0000000100d81660  x27: 0x0000000000000000
   x28: 0x0000000200c450ce   fp: 0x000000002c000000   lr: 0x0000000100d82fec
    sp: 0x0000000108d9bb70   pc: 0x0000000100d32940 cpsr: 0x80001000
   far: 0x0000000100d83000  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x200bff000 -        0x200c6afff dyld (*) <cef5a27a-d50b-3020-af03-1734b19bc8c5> /usr/lib/dyld
    0x7ff7ffd70000 -     0x7ff7ffd9ffff runtime (*) <21c1e0c9-a36e-3e4b-a12b-1bf54ce4403e> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=13.9M resident=0K(0%) swapped_out_or_unallocated=13.9M(100%)
Writable regions: Total=158.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=158.2M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    780K      192 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       13.1M        5 
VM_ALLOCATE (reserved)             124K       14         reserved VM address space (unallocated)
__DATA                            3684K       23 
__DATA_CONST                        80K        1 
__LINKEDIT                        1700K       20 
__TEXT                            12.3M       17 
dyld private memory               1024K        1 
mapped file                        6.0G       82 
===========                     =======  ======= 
TOTAL                              6.2G      365 
TOTAL, minus reserved VM space     6.2G      365 



-----------
Full Report
-----------

{"app_name":"GoldenDict","timestamp":"2022-02-17 04:08:05.00 +0800","app_version":"22.2","slice_uuid":"bd7e89da-4136-3973-8232-c25818b8a9a6","build_version":"","platform":1,"bundleID":"org.goldendict","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.1 (21C52)","incident_id":"407B756A-D421-40BB-B994-79542F357DE6","name":"GoldenDict"}
{
  "uptime" : 120000,
  "procLaunch" : "2022-02-17 04:08:05.7847 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "procStartAbsTime" : 2892064406129,
  "coalitionID" : 14290,
  "osVersion" : {
    "train" : "macOS 12.1",
    "build" : "21C52",
    "releaseType" : "User"
  },
  "captureTime" : "2022-02-17 04:08:05.8341 +0800",
  "incident" : "407B756A-D421-40BB-B994-79542F357DE6",
  "bug_type" : "309",
  "pid" : 14304,
  "procExitAbsTime" : 2892065548370,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "GoldenDict",
  "procPath" : "\/Applications\/GoldenDict.app\/Contents\/MacOS\/GoldenDict",
  "bundleInfo" : {"CFBundleShortVersionString":"22.2","CFBundleIdentifier":"org.goldendict"},
  "storeInfo" : {"deviceIdentifierForVendor":"20E85385-95CF-58B8-947C-3A481DE50E9C","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.goldendict",
  "crashReporterKey" : "A6B6719C-C5F7-9E96-8FDB-FF960C9921D3",
  "wakeTime" : 4878,
  "sleepWakeUUID" : "551F09B0-FD77-4330-B52E-FCFCBA35BCDC",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/libopencc.1.1.dylib","Referenced from: \/Applications\/GoldenDict.app\/Contents\/MacOS\/GoldenDict","Reason: tried: '\/Applications\/GoldenDict.app\/Contents\/MacOS\/..\/Frameworks\/libopencc.1.1.dylib' (no such file), '\/Applications\/GoldenDict.app\/Contents\/MacOS\/..\/Frameworks\/libopencc.1.1.dylib' (no such file), '\/usr\/local\/lib\/libopencc.1.1.dylib' (no such file), '\/usr\/lib\/libopencc.1.1.dylib' (no such file)"]},
  "asi" : {"dyld":["Library not loaded: @rpath\/libopencc.1.1.dylib","Referenced from: \/Applications\/GoldenDict.app\/Contents\/MacOS\/GoldenDict","Reason: tried: '\/Applications\/GoldenDict.app\/Contents\/MacOS\/..\/Frameworks\/libopencc.1.1.dylib' (no such file), '\/Applications\/GoldenDict.app\/Contents\/MacOS\/..\/Frameworks\/libopencc.1.1.dylib' (no such file), '\/usr\/local\/lib\/libopencc.1.1.dylib' (no such file), '\/usr\/lib\/libopencc.1.1.dylib' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1321217,"threadState":{"x":[{"value":6},{"value":1},{"value":12969499344},{"value":102},{"value":12969498320},{"value":0},{"value":15349147273332620452},{"value":138823075425},{"value":12969498320},{"value":0},{"value":102},{"value":12969498320},{"value":102},{"value":12969499344},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041298230128},{"value":4308762624},{"value":2047},{"value":4443475872},{"value":18446744073709551615},{"value":4308805908},{"value":8602890703,"symbolLocation":80,"symbol":"abort_with_payload_wrapper_internal"},{"value":4308804084},{"value":4309128800},{"value":0},{"value":8602800334,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4309135340},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4443454320},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4308805952,"matchesCrashFrame":1},"far":{"value":4309135360}},"frames":[{"imageOffset":4308805952,"region":"Rosetta Runtime Routines","symbolLocation":10560,"imageIndex":0},{"imageOffset":4309135340,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":377345,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":42515,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":25949,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3955,"imageIndex":1},{"imageOffset":21684,"symbol":"start","symbolLocation":388,"imageIndex":1}]},{"id":1321229,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18660,"imageIndex":2},{"imageOffset":71976,"imageIndex":2},{"imageOffset":77988,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8602513408,
    "size" : 442368,
    "uuid" : "cef5a27a-d50b-3020-af03-1734b19bc8c5",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703125929984,
    "size" : 196608,
    "uuid" : "21c1e0c9-a36e-3e4b-a12b-1bf54ce4403e",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703263342592,
  "size" : 15218081792,
  "uuid" : "e72a2011-6acf-3f25-bfe7-730570330401"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=13.9M resident=0K(0%) swapped_out_or_unallocated=13.9M(100%)\nWritable regions: Total=158.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=158.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    780K      192 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       13.1M        5 \nVM_ALLOCATE (reserved)             124K       14         reserved VM address space (unallocated)\n__DATA                            3684K       23 \n__DATA_CONST                        80K        1 \n__LINKEDIT                        1700K       20 \n__TEXT                            12.3M       17 \ndyld private memory               1024K        1 \nmapped file                        6.0G       82 \n===========                     =======  ======= \nTOTAL                              6.2G      365 \nTOTAL, minus reserved VM space     6.2G      365 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61fb0e87c773c43cde3bb80e"
      },
      "deploymentId" : 240000305
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000231
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000106
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "620161c8295c182621eced1f"
      },
      "deploymentId" : 240000389
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,1, BootROM 7429.61.2, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Oct 25 2021 22:17:59 version 20.10.853.26.8.7.107 FWID 01-417a4935
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
`

**Comment by xiaoyifang** [comment]
my thanks for your time to test
try install opencc with brew

```
brew install opencc
```

https://github.com/goldendict/goldendict/issues/1462

**Comment by xiaoyifang** [comment]
if above method works ,you can try this
https://github.com/xiaoyifang/goldendict/releases/tag/v22.2.alpha-81cff1f

**Comment by prenfic** [comment]
👌🏼 Any good news or bad news I will update you here

Regards,
Kaijian Lawrence Law
loc

**Comment by prenfic** [comment]
> if above method works ,you can try this
> https://github.com/xiaoyifang/goldendict/releases/tag/v22.2.alpha-81cff1f

<img width="559" alt="image" src="https://user-images.githubusercontent.com/13857562/154384235-426539ab-7c60-4582-ab13-b5a74ed0888d.png">
It's working
Gotta try with dict files

**Comment by xiaoyifang** [comment]
> > if above method works ,you can try this
> > https://github.com/xiaoyifang/goldendict/releases/tag/v22.2.alpha-81cff1f
> 
> <img alt="image" width="559" src="https://user-images.githubusercontent.com/13857562/154384235-426539ab-7c60-4582-ab13-b5a74ed0888d.png">
> 
> It's working Gotta try with dict files

this is a suprise to me. 👍

**Comment by nonwill** [comment]
[GoldenDict++OCR-macOS-12.13.1_universal based on Qt-5.15.3](https://github.com/nonwill/GoldenDict-OCR/releases/tag/test) has been released for test.

https://github.com/goldendict/goldendict/issues/1340#issuecomment-1117613476

**Comment by loyukfai** [comment]
Maybe you can try these?

https://github.com/xiaoyifang/goldendict/releases

**Comment by GPLv3-fan** [comment]
@nonwill do not promote your malware here. First, begin to respect the GPLv3 License instead of stealing code.

@nonwill became a "laughing stock" of everyone ! lol
