### ISSUE TITLE
qt-style-st-lingoes.css the file was missing

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1459]
as title.

**Comment by vedgy** [comment]
eef66a8f0f96f8867ad446ec3135704f1daf904f added a "lingoes" style. The very next commit 994eb998e95fceb0a294f59500fe6f2ebbe6bb1f renamed it to "lingoes-blue", including the rename from *qt-style-st-lingoes.css* to *qt-style-st-lingoes-blue.css*.

The absence of *qt-style-st-lingoes.css* might be intentional, if the default Qt settings are deliberately used in the style. Do you see any issues with the looks of the current "lingoes" style? Would copying *qt-style-st-lingoes-blue.css* to *qt-style-st-lingoes.css* fix them?

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/153751862-5e6f48da-0b57-4303-add2-9753a029de06.png)
they are two different style.

> Would copying qt-style-st-lingoes-blue.css to qt-style-st-lingoes.css fix them?

would fix warning. did not know if have some side effect.
