### ISSUE TITLE
how about to remove maclibs and use homebrew to manage the package on macos

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1462]

**Comment by shawkynasr** [comment]
Homebrew is better, as well it supports the Mac M1 chip.

**Comment by xiaoyifang** [comment]
wish someone can contribute a commit .
I have no knowlege of macos usage.

**Comment by shawkynasr** [comment]
[win-ubuntu-macos-staged-20220216](https://github.com/xiaoyifang/goldendict/releases/tag/v22.2.alpha-9075111)
win-ubuntu-macos-staged-20220215

Doesn't work, every time open it there are are error:

`-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               GoldenDict [3152]
Path:                  /Applications/GoldenDict.app/Contents/MacOS/GoldenDict
Identifier:            org.goldendict
Version:               22.2 (???)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2022-02-17 01:52:06.3822 +0800
OS Version:            macOS 12.2.1 (21D62)
Report Version:        12
Bridge OS Version:     6.2 (19P744)
Anonymous UUID:        760E11E7-D494-D8B4-1453-212F341309BD

Sleep/Wake UUID:       26C49D5D-838E-4D67-B9A5-47A2D0995DCE

Time Awake Since Boot: 10000 seconds
Time Since Wake:       208 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/libopencc.1.1.dylib
Referenced from: /Applications/GoldenDict.app/Contents/MacOS/GoldenDict
Reason: tried: '/Applications/GoldenDict.app/Contents/MacOS/../Frameworks/libopencc.1.1.dylib' (no such file), '/Applications/GoldenDict.app/Contents/MacOS/../Frameworks/libopencc.1.1.dylib' (no such file), '/usr/local/lib/libopencc.1.1.dylib' (no such file), '/usr/lib/libopencc.1.1.dylib' (no such file)
(terminated at launch; ignore backtrace)

Application Specific Information:
Library not loaded: @rpath/libopencc.1.1.dylib
Referenced from: /Applications/GoldenDict.app/Contents/MacOS/GoldenDict
Reason: tried: '/Applications/GoldenDict.app/Contents/MacOS/../Frameworks/libopencc.1.1.dylib' (no such file), '/Applications/GoldenDict.app/Contents/MacOS/../Frameworks/libopencc.1.1.dylib' (no such file), '/usr/local/lib/libopencc.1.1.dylib' (no such file), '/usr/lib/libopencc.1.1.dylib' (no such file)


Thread 0 Crashed:
0   dyld                          	       0x106eed0ce __abort_with_payload + 10
1   dyld                          	       0x106f031cf abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x106f03201 abort_with_payload + 9
3   dyld                          	       0x106eb1613 dyld4::halt(char const*) + 375
4   dyld                          	       0x106ead55d dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3955
5   dyld                          	       0x106eac4b4 start + 388


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7bbcfc668  rdx: 0x00007ff7bbcfcad0
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7bbcfc6b0  rsp: 0x00007ff7bbcfc668
   r8: 0x00007ff7bbcfc6d0   r9: 0x0000000000000000  r10: 0x0000000000000066  r11: 0x0000000000000246
  r12: 0x0000000000000066  r13: 0x00007ff7bbcfcad0  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x0000000106eed0ce  rfl: 0x0000000000000246  cr2: 0x0000700009a5abc8
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133


Binary Images:
       0x106ea7000 -        0x106f12fff dyld (*) <7de33963-bbc5-3996-ba6e-f1d562c17c95> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=13.3M resident=0K(0%) swapped_out_or_unallocated=13.3M(100%)
Writable regions: Total=12.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.1M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                            3588K       19 
__DATA_CONST                        80K        1 
__LINKEDIT                        1636K       16 
__TEXT                            11.7M       15 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                             81.9M       57 

`

**Comment by xiaoyifang** [comment]
may caused by my careless upgrade opencc to ocd2.

can you try install opencc manually and try again .

```
brew install opencc

```

**Comment by xiaoyifang** [comment]
or try this
https://github.com/xiaoyifang/goldendict/releases/tag/v22.2.alpha-81cff1f

**Comment by shawkynasr** [comment]
It works now, many thanks!
