### ISSUE TITLE
Goldendict in Portable mode disallows adding dictionaries search paths, relevant config file edits are discarded.

### ISSUE THREAD

**Issue by gavenkoa** [goldendict/goldendict#1560]
I installed Goldendict via `scoop`. It comes as Portable (there is s directory `portable` with a file `config`).

I cannot add another directory to the list of directories to scan dictionaries from, the only predefined `content` is in the list and there is no way to add anything other.

If I edit `config` outside of Goldendict and start the app it discards my alterations.

Scoop installed software is permanently installed but prefer portable mode to handle hassle free upgrades.

As a **workaround** I created directory junction in `content` directory pointing to the actual dictionary location.

**Comment by xiaoyifang** [comment]
try to delete the directory `portable`

**Comment by gavenkoa** [comment]
There is a high chance the package manager `scoop` recreates that directory on the version upgrade.

I just presented the case when the app is installed as portable but actually it is local and functionality was limited for questionable reason. The better is to allow and warn than forbid without obvious reason (no warning in the UI why "Add" button is disabled).

**Comment by StructSeeker** [comment]
I (using another github account) submitted the pull-request which set Goldendict to be portable, about which the the help of Goldendict provides the following information:
>03 Portable mode 
Usually GoldenDict store all program settings and dictionary indexes in home folder of current user. In portable mode program settings and dictionary indexes stored in "portable" folder beside the main program file. This mode suit for using of GoldenDict with common settings directly from flash drive on different computers.
To turn on portable mode it needs only create "portable" folder beside the main program file. If such folder exists GoldenDict will launched in portable mode.
In portable mode GoldenDict works with some limitations:
You can't select folders with dictionaries. All dictionaries should be placed in "contents" folder beside the main program file and/or its subfolders.
You can't use sound files in separate folders. 

As far as i am concerned, the "default portable style" (i.e. hosting the portable and content folder in [persist folder](https://github.com/ScoopInstaller/Scoop/wiki/Persistent-data) of scoop via symbol link) conforms with the philosophy and guideline of scoop (perference for portable mode). Since the persist folder is configured in the manifest and might be re-created after each update, if you want a default-nonportable goldendict, the best way is probably to create and submit another goldendict-nonportable to the scoop/extra repository.

**Comment by vedgy** [comment]
Would by any chance removing the `portable` directory and creating an empty `portable` *file* in its place prevent scoop from recreating the directory during an update? GoldenDict should ignore the `portable` *file* due to this code:
```cpp
isPortable( QFileInfo( portableHomeDirPath() ).isDir()
```

**Comment by StructSeeker** [comment]
> Would by any chance removing the `portable` directory and creating an empty `portable` _file_ in its place prevent scoop from recreating the directory during an update? GoldenDict should ignore the `portable` _file_ due to this code:
> 
> ```c++
> isPortable( QFileInfo( portableHomeDirPath() ).isDir() )
> ```

Personally, I wouldn't write code depending on implementation. But if the "directory convention" can be guaranteed, it's indeed possible to add a script in the scoop manifest which scoop user can run after install goldendict such that the goldendict is set to nonportable and won't be reset by scoop during upgrade.

**Comment by vedgy** [comment]
> But if the "directory convention" can be guaranteed

GoldenDict almost never breaks backward compatibility these days, so this convention is highly likely to stay for a long time.

But there may be other portable vs non-portable differences, which would complicate the simple matter of the `portable` dir [non]existence. GoldenDict looks for its data and cache files either in a directory relative to the executable location or in an absolute-path directory, depending on portable mode. If scoop installs some data for GoldenDict, it may have to be installed to a different location in nonportable mode.

**Comment by StructSeeker** [comment]
> If scoop installs some data for GoldenDict, it may have to be installed to a different location in nonportable mode.
Exactly, Unless read the config of goldendict by script, there is no way for scoop to know the absolute path. On the other hand, the relative path can be easily persisted with directory junction under current scoop mechanics.

**Comment by gavenkoa** [comment]
So the only **surprise is grayed inactive button for adding dictionaries** when Goldendict is in portable mode.

The best what can be done is to show a message box with the text explaining that alternative paths are forbidden because of portable mode. A disabled button hardly tells anything.

**Comment by StructSeeker** [comment]
> So the only **surprise is grayed inactive button for adding dictionaries** when Goldendict is in portable mode.
> 
> The best what can be done is to show a message box with the text explaining that alternative paths are forbidden because of portable mode. A disabled button hardly tells anything.

I suppose adding note in scoop manifest alerting about the portable mode might also be a good idea.

**Comment by vedgy** [comment]
![sources-in-portable-mode](https://github.com/goldendict/goldendict/assets/5929075/1a34b3c1-80af-43a5-8a95-7c37307ce166)

How about this UI?

**Comment by gavenkoa** [comment]
> How about this UI?

It is awesome!
